import type { NetworkGroup } from './network-group.types.js';

/**
 * Describes the network group to create.
 */
export interface CreateNetworkGroupCommandInput {
  /** Identifier of the organisation the network group belongs to. */
  ownerId: string;
  /** Human readable name of the network group. */
  label?: string;
  /** Free form description of the network group. */
  description?: string;
  /** Tags to attach to the network group. */
  tags?: Array<string>;
  /** Members to add to the network group right away. */
  members?: Array<{
    /** Identifier of the member: an application id, an add-on real id, or an `external_<uuid>` id. */
    id: string;
    /** Human readable name of the member. */
    label?: string;
  }>;
}

/**
 * The network group as it exists once the platform has created it.
 */
export type CreateNetworkGroupCommandOutput = NetworkGroup;

/**
 * Describes the network group to create, with the id generated by the composite command.
 */
export interface CreateNetworkGroupCommandInnerInput extends CreateNetworkGroupCommandInput {
  /** Identifier to give to the network group, generated client side so that it can be polled afterwards. */
  networkGroupId: string;
}
