/**
 * A billing document issued to an owner for one consumption period: the legal identity it is
 * addressed to, the detailed lines it bills, and how far its payment got.
 */
export interface Invoice {
  /**
   * Number identifying the document, of the form `YYYYMMDDNNNN`.
   * @renamedFrom `invoice_number`
   */
  invoiceNumber: string;
  /** Nature of the document: `INVOICE`, or `CREDITNOTE` when it voids one. */
  kind: 'INVOICE' | 'CREDITNOTE';
  /** Whether the document was generated by the billing system or created by hand by an admin. */
  origin: 'automatic' | 'manual';
  /**
   * Which iteration of the billing model the document was produced with, as a stringified integer:
   * `0` for the legacy model and `1` or `2` for the newer ones.
   */
  version: string;
  /** Broad family of what is billed, mostly `PAAS`. */
  category?: string;
  /** Legal identity and address the document is addressed to. */
  address: InvoiceAddress;
  /**
   * When the document was issued.
   * @renamedFrom `emission_date`
   * @converted to an ISO date string
   */
  emittedAt: string;
  /**
   * When the document was paid, if it was.
   * @renamedFrom `pay_date`
   * @converted to an ISO date string
   */
  paidAt?: string;
  /** How far the payment of the document got. */
  status: InvoiceStatus;
  /**
   * Start of the period the billed consumption was measured over.
   * @renamedFrom `consumption_begin_date`
   * @converted to an ISO date string
   */
  consumptionStartedAt: string;
  /**
   * End of the period the billed consumption was measured over.
   * @renamedFrom `consumption_end_date`
   * @converted to an ISO date string
   */
  consumptionEndedAt: string;
  /** Currency every amount of the document is expressed in. */
  currency: string;
  /**
   * How many months the amount is spread over when computing the internal indicators.
   * @renamedFrom `kpi_compute_months`
   */
  kpiComputeMonths: number;
  /**
   * Factor applied to every price of the document.
   * @renamedFrom `price_factor`
   */
  priceFactor: number;
  /** Discount applied to the whole document, in percent. */
  discount: number;
  /**
   * VAT rate applied to the total, in percent.
   * @renamedFrom `vat_percent`
   */
  vatPercent: number;
  /** Lines billing the uptime of the instances, one per application or add-on. */
  uptimes: Array<InvoiceUptime>;
  /** Lines billing a metered quantity, one per application or add-on and unit. */
  countables: Array<InvoiceCountable>;
  /**
   * Lines billing what was consumed on a third party vendor.
   * @renamedFrom `vendor_consumption`
   */
  vendorConsumptions: Array<InvoiceVendorConsumption>;
  /**
   * Lines added by hand, carrying their own description.
   * @renamedFrom `classic`
   */
  extraItems: Array<InvoiceExtraItem>;
  /**
   * Instance uptimes that were measured but could not be billed.
   * @renamedFrom `unusable`
   */
  unbilledUptimes: Array<InvoiceUnbilledUptime>;
  /**
   * Credit the owner had left when the document was issued.
   * @renamedFrom `credit_balance_at_emission`
   */
  creditBalanceAtEmission: InvoiceMoney;
  /**
   * Free credits, per coupon, still usable over the period this document covers.
   * @renamedFrom `free_credits_available_this_period`
   */
  freeCreditsAvailableThisPeriod: Array<InvoiceCouponRemains>;
  /**
   * Free credits, per coupon, that will still be usable over the next period.
   * @renamedFrom `free_credits_available_next_period`
   */
  freeCreditsAvailableNextPeriod: Array<InvoiceCouponRemains>;
  /**
   * Sum of the upfront amounts of every invoice still pending when this document was issued.
   * @renamedFrom `total_pending_upfront_before_emission`
   */
  totalPendingUpfrontBeforeEmission: InvoiceMoney;
  /**
   * Credit bought upfront on this document.
   * @renamedFrom `upfront_credit_amount`
   */
  upfrontCreditAmount: InvoiceMoney;
  /**
   * Order reference the customer asked to have printed on the document.
   * @renamedFrom `customer_order_id`
   */
  customerOrderId?: string;
  /**
   * Provider the payment went through, for example Stripe or PayPal.
   * @renamedFrom `payment_provider`
   */
  paymentProvider?: string;
  /**
   * Identifier of the payment method the document was charged on.
   * @renamedFrom `payment_method_id`
   */
  paymentMethodId?: string;
  /**
   * Identifier of the transaction at the payment provider.
   * @renamedFrom `provider_transaction_id`
   */
  providerTransactionId?: string;
  /**
   * Last response or error the payment provider returned for this document.
   * @renamedFrom `provider_last_response`
   */
  providerLastResponse?: string;
  /**
   * Identifier of the VAT declaration this document was declared in.
   * @renamedFrom `vat_declaration_id`
   */
  vatDeclarationId?: string;
  /**
   * Total to pay, taxes excluded, computed by the API.
   * @renamedFrom `total_tax_excluded`
   */
  totalTaxExcluded: InvoiceMoney;
  /**
   * Total tax due on top of it, computed by the API.
   * @renamedFrom `total_tax`
   */
  totalTax: InvoiceMoney;
}

/**
 * A billing document as it appears in a listing: its identity, its totals and its payment state,
 * without any of the detailed lines.
 */
export interface InvoiceSummary {
  /**
   * Number identifying the document, of the form `YYYYMMDDNNNN`.
   * @renamedFrom `invoice_number`
   */
  invoiceNumber: string;
  /** Nature of the document: `INVOICE`, or `CREDITNOTE` when it voids one. */
  kind: 'INVOICE' | 'CREDITNOTE';
  /** Broad family of what is billed, mostly `PAAS`. */
  category?: string;
  /** Legal identity and address the document is addressed to. */
  address: InvoiceAddress;
  /**
   * When the document was issued.
   * @renamedFrom `emission_date`
   */
  emittedAt: string;
  /**
   * When the document was paid, if it was.
   * @renamedFrom `pay_date`
   */
  paidAt?: string;
  /** How far the payment of the document got. */
  status: InvoiceStatus;
  /** Currency every amount of the document is expressed in. */
  currency: string;
  /**
   * How many months the amount is spread over when computing the internal indicators.
   * @renamedFrom `kpi_compute_months`
   */
  kpiComputeMonths: number;
  /**
   * Factor applied to every price of the document.
   * @renamedFrom `price_factor`
   */
  priceFactor: number;
  /** Discount applied to the whole document, in percent. */
  discount: number;
  /**
   * VAT rate applied to the total, in percent.
   * @renamedFrom `vat_percent`
   */
  vatPercent: number;
  /**
   * Total to pay, taxes excluded.
   * @renamedFrom `total_tax_excluded`
   */
  totalTaxExcluded: InvoiceMoney;
  /**
   * Total tax due on top of it.
   * @renamedFrom `total_tax`
   */
  totalTax: InvoiceMoney;
  /**
   * Provider the payment went through, for example Stripe or PayPal.
   * @renamedFrom `payment_provider`
   */
  paymentProvider?: string;
  /**
   * Identifier of the transaction at the payment provider.
   * @renamedFrom `transaction_id`
   */
  transactionId?: string;
  /**
   * Order reference the customer asked to have printed on the document.
   * @renamedFrom `customer_order_id`
   */
  customerOrderId?: string;
  /**
   * How many days the document has been overdue for, once its payment grace period has run out, and `0` while it is
   * still within it. Only set for a document that is `PENDING` or `PAYMENTHELD`.
   * @renamedFrom `invoice_day_plan`
   */
  invoiceDayPlan?: number;
}

/**
 * How far the payment of a billing document got: `PENDING` when it is waiting to be charged,
 * `PROCESSING` when a payment is under way, `PAYMENTHELD` when charging attempts were deliberately
 * suspended, `PAID` when the funds were received, `CANCELED` when it was voided before any funds
 * were received, `REFUNDED` when it was voided after they were, `WONTPAY` when it was written
 * off, and `LOSS` when it was booked as a loss.
 */
export type InvoiceStatus =
  | 'PENDING'
  | 'PROCESSING'
  | 'PAYMENTHELD'
  | 'PAID'
  | 'CANCELED'
  | 'REFUNDED'
  | 'WONTPAY'
  | 'LOSS';

/**
 * The legal identity and address a billing document is addressed to, frozen as it was when the
 * document was issued.
 */
export interface InvoiceAddress {
  /**
   * Identifier of the address.
   * @renamedFrom `address_id`
   */
  id: string;
  /** Name of the customer, most likely a person's name. */
  name: string;
  /** Legal name of the company, when the customer is one. */
  company?: string;
  /** Street address of the customer. */
  address: string;
  /** City of the customer address. */
  city: string;
  /** Zip code of the customer address. */
  zipcode: string;
  /**
   * Two letter country code of the customer address.
   * @renamedFrom `country_alpha2`
   */
  country: string;
  /**
   * European VAT number of the customer.
   * @renamedFrom `vat_number`
   */
  vatNumber?: string;
  /**
   * VAT rate to apply, in percent.
   * @renamedFrom `vat_percent`
   */
  vatPercent: number;
  /**
   * Cost centre the customer asked to have printed on the document.
   * @renamedFrom `customer_cost_center`
   */
  customerCostCenter?: string;
  /**
   * Purchase order the customer asked to have printed on the document.
   * @renamedFrom `customer_purchase_order`
   */
  customerPurchaseOrder?: string;
}

/**
 * A line billing how long the instances of one application or add-on ran over the period.
 */
export interface InvoiceUptime {
  /**
   * Identifier of the billing line.
   * @renamedFrom `item_id`
   */
  id: string;
  /** Total price of the line, already computed from the details. */
  price: InvoiceMoney;
  /**
   * Identifier of the application or add-on the instances belong to.
   * @renamedFrom `app_id`
   */
  applicationId: string;
  /**
   * Identifier of the owner the application or add-on belongs to.
   * @renamedFrom `owner_id`
   */
  ownerId: string;
  /** One entry per instance run, given for reference. */
  details: Array<InvoiceUptimeDetail>;
  /** Procurement category the line falls into, for example `PaaS` or `IaaS`. */
  category: string;
  /**
   * Procurement sub-category the line falls into, for example `Bases de données`.
   * @renamedFrom `sub_category`
   */
  subCategory: string;
}

/**
 * One instance run billed on an uptime line, bounded by the measurement window.
 */
export interface InvoiceUptimeDetail {
  /**
   * Identifier of the instance.
   * @renamedFrom `instance_id`
   */
  instanceId: string;
  /**
   * Name of the scaler size the instance ran on.
   * @renamedFrom `flavor_name`
   */
  flavorName: string;
  /**
   * Identifier of the zone the instance ran in.
   * @renamedFrom `zone_id`
   */
  zone: string;
  /**
   * Identifier of the pricing policy the price was computed with.
   * @renamedFrom `runtime_policy_id`
   */
  policyId: string;
  /** Price of this run. */
  price: InvoiceMoney;
  /**
   * When the run started being measured, that is the later of the instance boot and the start of the period.
   * @renamedFrom `consumption_start`
   * @converted to an ISO date string
   */
  consumptionStartedAt: string;
  /**
   * When the run stopped being measured, that is the earlier of the instance shutdown and the end of the period.
   * @renamedFrom `consumption_end`
   * @converted to an ISO date string
   */
  consumptionEndedAt: string;
}

/**
 * A line billing a metered quantity consumed by one application or add-on over the period, such as
 * stored bytes or users.
 */
export interface InvoiceCountable {
  /**
   * Identifier of the billing line.
   * @renamedFrom `item_id`
   */
  id: string;
  /** Total price of the line, already computed from the details. */
  price: InvoiceMoney;
  /**
   * Identifier of the application or add-on that consumed the quantity.
   * @renamedFrom `app_id`
   */
  applicationId: string;
  /**
   * Identifier of the owner the application or add-on belongs to.
   * @renamedFrom `owner_id`
   */
  ownerId: string;
  /** Name of the metered service. */
  service: string;
  /**
   * Name of the unit the quantity is counted in, for example `B` or `User`.
   * @renamedFrom `unit_name`
   */
  unitName: string;
  /**
   * Identifier of the zone the consumption happened in.
   * @renamedFrom `zone_id`
   */
  zone: string;
  /**
   * Identifier of the pricing policy the price was computed with.
   * @renamedFrom `policy_id`
   */
  policyId: string;
  /** Quantity billed on the line, in the unit named above. */
  quantity?: number;
  /**
   * Identifier of the pricing plan the quantity falls into.
   * @renamedFrom `plan_id`
   */
  planId?: string;
  /** How long the consumption lasted, when the line is time bounded. */
  duration?: string;
  /**
   * Sum of the prices of the details, which may differ from the line price.
   * @renamedFrom `details_price`
   */
  detailsPrice?: InvoiceMoney;
  /** One entry per measure, given for reference. */
  details: Array<InvoiceCountableDetail>;
  /** Procurement category the line falls into, for example `PaaS` or `IaaS`. */
  category: string;
  /**
   * Procurement sub-category the line falls into, for example `Bases de données`.
   * @renamedFrom `sub_category`
   */
  subCategory: string;
}

/**
 * One measure of a metered quantity billed on a countable line.
 */
export interface InvoiceCountableDetail {
  /**
   * When the measure started.
   * @renamedFrom `consumption_start`
   * @converted to an ISO date string
   */
  consumptionStartedAt?: string;
  /**
   * When the measure ended.
   * @renamedFrom `consumption_end`
   * @converted to an ISO date string
   */
  consumptionEndedAt?: string;
  /**
   * Identifier of the pricing plan the measure falls into.
   * @renamedFrom `plan_id`
   */
  planId: string;
  /** Quantity counted between the two boundaries. */
  quantity?: number;
  /** Price of this measure. */
  price: InvoiceMoney;
}

/**
 * A line billing what one application consumed on a third party vendor resold by Clever Cloud.
 */
export interface InvoiceVendorConsumption {
  /**
   * Identifier of the billing line.
   * @renamedFrom `item_id`
   */
  itemId: string;
  /** Price of the line. */
  price: InvoiceMoney;
  /**
   * Identifier of the vendor the consumption happened on.
   * @renamedFrom `vendor_id`
   */
  vendorId: string;
  /**
   * Identifier of the owner the application belongs to.
   * @renamedFrom `owner_id`
   */
  ownerId: string;
  /**
   * Identifier of the application that consumed on the vendor.
   * @renamedFrom `app_id`
   */
  applicationId: string;
}

/**
 * A line added by hand to a billing document, priced as
 * `unitPrice × quantity × priceFactor × (100 - discount) / 100`.
 */
export interface InvoiceExtraItem {
  /**
   * Identifier of the billing line.
   * @renamedFrom `item_id`
   */
  id: string;
  /**
   * Price of a single unit.
   * @renamedFrom `unit_price`
   */
  unitPrice: InvoiceMoney;
  /** How many units are billed. */
  quantity: number;
  /**
   * Factor applied to this line only, overriding the one of the document.
   * @renamedFrom `price_factor`
   */
  priceFactor?: number;
  /** Discount applied to this line only, in percent, overriding the one of the document. */
  discount?: number;
  /** What is billed, written by hand and therefore already in the customer's language. */
  description: string;
  /**
   * Further details about what is billed, also written by hand.
   * @renamedFrom `sub_description`
   */
  subDescription?: string;
  /**
   * Identifier of the recurring billing item this line was generated from.
   * @renamedFrom `classic_billing_item_id`
   */
  classicBillingItemId?: string;
  /**
   * Identifier of the owner the line is billed to.
   * @renamedFrom `owner_id`
   */
  ownerId: string;
  /** Procurement category the line falls into, for example `PaaS` or `IaaS`. */
  category: string;
  /**
   * Procurement sub-category the line falls into, for example `Autres Prestations`.
   * @renamedFrom `sub_category`
   */
  subCategory: string;
}

/**
 * An instance run that was measured over the period but could not be turned into a billing line,
 * kept on the document for reference.
 */
export interface InvoiceUnbilledUptime {
  /**
   * Identifier of the entry.
   * @renamedFrom `item_id`
   */
  id: string;
  /**
   * Identifier of the zone the instance ran in.
   * @renamedFrom `zone_id`
   */
  zone: string;
  /**
   * Name of the scaler size the instance ran on.
   * @renamedFrom `flavor_name`
   */
  flavorName: string;
  /** Machine the instance ran on. */
  host: string;
  /**
   * Kind of image the instance was booted from.
   * @renamedFrom `image_type`
   */
  imageType?: string;
  /**
   * When the run started being measured.
   * @renamedFrom `start_date`
   */
  consumptionStartedAt: string;
  /**
   * When the run stopped being measured.
   * @renamedFrom `end_date`
   */
  consumptionEndedAt: string;
}

/**
 * An amount of money, with the currency it is expressed in.
 */
export interface InvoiceMoney {
  /** The amount, rounded to two decimal places. */
  amount: number;
  /** ISO code of the currency, for example `EUR`. */
  currency: string;
}

/**
 * What is left of the free credits one coupon granted.
 */
export interface InvoiceCouponRemains {
  /** Name of the coupon the credits came from. */
  name: string;
  /** Credits still available on that coupon. */
  remaining: InvoiceMoney;
}
