name: Release
on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write # Required for npm OIDC trusted publishing

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: '[Prepare] Checkout'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: '[Prepare] Setup'
        uses: ./.github/actions/ci-setup
      - name: '[Release] Version or publish packages'
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: 'chore: release'
          title: 'Release'
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
